import { Match } from '@/types/match';

export const mockMatches: Match[] = [
  {
    id: 'match-001',
    gender: 'men',
    stage: 'group',
    group: 'A',
    matchday: 1,
    home: 'France',
    away: 'United States',
    kickoff: '2024-07-24T19:00:00+02:00',
    venue: 'Parc des Princes',
    city: 'Paris',
  },
  {
    id: 'match-002',
    gender: 'men',
    stage: 'group',
    group: 'A',
    matchday: 1,
    home: 'Guinea',
    away: 'New Zealand',
    kickoff: '2024-07-24T16:00:00+02:00',
    venue: 'Allianz Riviera',
    city: 'Nice',
  },
  {
    id: 'match-003',
    gender: 'men',
    stage: 'group',
    group: 'B',
    matchday: 1,
    home: 'Argentina',
    away: 'Morocco',
    kickoff: '2024-07-24T22:00:00+02:00',
    venue: 'Stade Geoffroy-Guichard',
    city: 'Saint-Étienne',
  },
  {
    id: 'match-004',
    gender: 'men',
    stage: 'group',
    group: 'C',
    matchday: 1,
    home: 'Spain',
    away: 'Egypt',
    kickoff: '2024-07-24T16:00:00+02:00',
    venue: 'Orange Vélodrome',
    city: 'Marseille',
  },
  {
    id: 'match-005',
    gender: 'men',
    stage: 'group',
    group: 'D',
    matchday: 1,
    home: 'Japan',
    away: 'Mali',
    kickoff: '2024-07-24T13:00:00+02:00',
    venue: 'Groupama Stadium',
    city: 'Lyon',
  },
  {
    id: 'match-006',
    gender: 'women',
    stage: 'group',
    group: 'A',
    matchday: 1,
    home: 'United States',
    away: 'Zambia',
    kickoff: '2024-07-25T13:00:00+02:00',
    venue: 'Orange Vélodrome',
    city: 'Marseille',
  },
  {
    id: 'match-007',
    gender: 'women',
    stage: 'group',
    group: 'B',
    matchday: 1,
    home: 'France',
    away: 'Colombia',
    kickoff: '2024-07-25T19:00:00+02:00',
    venue: 'Groupama Stadium',
    city: 'Lyon',
  },
  {
    id: 'match-008',
    gender: 'women',
    stage: 'group',
    group: 'C',
    matchday: 1,
    home: 'Spain',
    away: 'Japan',
    kickoff: '2024-07-25T16:00:00+02:00',
    venue: 'Parc des Princes',
    city: 'Paris',
  },
  {
    id: 'match-009',
    gender: 'men',
    stage: 'group',
    group: 'A',
    matchday: 2,
    home: 'France',
    away: 'Guinea',
    kickoff: '2024-07-27T19:00:00+02:00',
    venue: 'Parc des Princes',
    city: 'Paris',
  },
  {
    id: 'match-010',
    gender: 'men',
    stage: 'group',
    group: 'B',
    matchday: 2,
    home: 'Morocco',
    away: 'Iraq',
    kickoff: '2024-07-27T22:00:00+02:00',
    venue: 'Matmut Atlantique',
    city: 'Bordeaux',
  },
  {
    id: 'match-011',
    gender: 'women',
    stage: 'group',
    group: 'A',
    matchday: 2,
    home: 'Germany',
    away: 'Australia',
    kickoff: '2024-07-28T13:00:00+02:00',
    venue: 'Allianz Riviera',
    city: 'Nice',
  },
  {
    id: 'match-012',
    gender: 'women',
    stage: 'group',
    group: 'C',
    matchday: 2,
    home: 'Brazil',
    away: 'Nigeria',
    kickoff: '2024-07-28T16:00:00+02:00',
    venue: 'Stade Geoffroy-Guichard',
    city: 'Saint-Étienne',
  },
  {
    id: 'match-013',
    gender: 'men',
    stage: 'group',
    group: 'C',
    matchday: 2,
    home: 'Dominican Republic',
    away: 'Japan',
    kickoff: '2024-07-27T13:00:00+02:00',
    venue: 'Matmut Atlantique',
    city: 'Bordeaux',
  },
  {
    id: 'match-014',
    gender: 'men',
    stage: 'group',
    group: 'D',
    matchday: 3,
    home: 'Uzbekistan',
    away: 'Paraguay',
    kickoff: '2024-07-30T16:00:00+02:00',
    venue: 'Allianz Riviera',
    city: 'Nice',
  },
  {
    id: 'match-015',
    gender: 'men',
    stage: 'quarter-final',
    group: null,
    matchday: null,
    home: 'France',
    away: 'Argentina',
    kickoff: '2024-08-02T17:00:00+02:00',
    venue: 'Parc des Princes',
    city: 'Paris',
  },
  {
    id: 'match-016',
    gender: 'men',
    stage: 'quarter-final',
    group: null,
    matchday: null,
    home: 'Morocco',
    away: 'United States',
    kickoff: '2024-08-02T17:00:00+02:00',
    venue: 'Groupama Stadium',
    city: 'Lyon',
  },
  {
    id: 'match-017',
    gender: 'men',
    stage: 'semi-final',
    group: null,
    matchday: null,
    home: 'France',
    away: 'Egypt',
    kickoff: '2024-08-05T18:00:00+02:00',
    venue: 'Parc des Princes',
    city: 'Paris',
  },
  {
    id: 'match-018',
    gender: 'men',
    stage: 'bronze-medal',
    group: null,
    matchday: null,
    home: 'Morocco',
    away: 'Egypt',
    kickoff: '2024-08-08T17:00:00+02:00',
    venue: 'Groupama Stadium',
    city: 'Lyon',
  },
  {
    id: 'match-019',
    gender: 'men',
    stage: 'gold-medal',
    group: null,
    matchday: null,
    home: 'France',
    away: 'Spain',
    kickoff: '2024-08-09T21:00:00+02:00',
    venue: 'Parc des Princes',
    city: 'Paris',
  },
  {
    id: 'match-020',
    gender: 'women',
    stage: 'quarter-final',
    group: null,
    matchday: null,
    home: 'United States',
    away: 'Japan',
    kickoff: '2024-08-03T17:00:00+02:00',
    venue: 'Orange Vélodrome',
    city: 'Marseille',
  },
  {
    id: 'match-021',
    gender: 'women',
    stage: 'quarter-final',
    group: null,
    matchday: null,
    home: 'France',
    away: 'Canada',
    kickoff: '2024-08-03T20:00:00+02:00',
    venue: 'Parc des Princes',
    city: 'Paris',
  },
  {
    id: 'match-022',
    gender: 'women',
    stage: 'semi-final',
    group: null,
    matchday: null,
    home: 'United States',
    away: 'Germany',
    kickoff: '2024-08-06T18:00:00+02:00',
    venue: 'Parc des Princes',
    city: 'Paris',
  },
  {
    id: 'match-023',
    gender: 'women',
    stage: 'bronze-medal',
    group: null,
    matchday: null,
    home: 'Germany',
    away: 'France',
    kickoff: '2024-08-09T17:00:00+02:00',
    venue: 'Groupama Stadium',
    city: 'Lyon',
  },
  {
    id: 'match-024',
    gender: 'women',
    stage: 'gold-medal',
    group: null,
    matchday: null,
    home: 'United States',
    away: 'Brazil',
    kickoff: '2024-08-10T21:00:00+02:00',
    venue: 'Parc des Princes',
    city: 'Paris',
  },
];
